"""change_tags_column_to_jsonb

Revision ID: 111e5b3d61af
Revises: 4c41c5ec190a
Create Date: 2026-03-25 21:41:30.696024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '111e5b3d61af'
down_revision: Union[str, Sequence[str], None] = '4c41c5ec190a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to properly convert JSON to JSONB with USING clause
    op.execute("ALTER TABLE resources ALTER COLUMN tags TYPE JSONB USING tags::jsonb")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to properly convert JSONB back to JSON
    op.execute("ALTER TABLE resources ALTER COLUMN tags TYPE JSON USING tags::json")
    # ### end Alembic commands ###
