"""Add fetch_tier and fetch_error_type to resources

Revision ID: 4c41c5ec190a
Revises: 3f9bf45c8ac2
Create Date: 2026-03-25 21:23:21.001977

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c41c5ec190a"
down_revision: Union[str, Sequence[str], None] = "3f9bf45c8ac2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resources", sa.Column("fetch_tier", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "resources",
        sa.Column("fetch_error_type", sa.String(length=30), nullable=True),
    )
    op.alter_column(
        "resources",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resources",
        "tags",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("resources", "fetch_error_type")
    op.drop_column("resources", "fetch_tier")
    # ### end Alembic commands ###
