"""Update resources table for DEV-013

Revision ID: 9141aa9e76e4
Revises: cc7c5f32e20b
Create Date: 2026-03-15 17:25:45.669086

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9141aa9e76e4"
down_revision: Union[str, Sequence[str], None] = "cc7c5f32e20b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with defaults first
    op.add_column("resources", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.add_column("resources", sa.Column("content_type", sa.String(), nullable=True))
    op.add_column("resources", sa.Column("original_content", sa.Text(), nullable=True))
    op.add_column("resources", sa.Column("prefer_provider", sa.String(), nullable=True))

    # Copy data from old columns to new columns
    op.execute("UPDATE resources SET owner_id = user_id")
    op.execute("UPDATE resources SET content_type = 'url'")
    op.execute(
        "UPDATE resources SET original_content = COALESCE(url, raw_text, 'migrated')"
    )

    # Make new columns non-nullable
    op.alter_column("resources", "owner_id", nullable=False)
    op.alter_column("resources", "content_type", nullable=False)
    op.alter_column("resources", "original_content", nullable=False)

    # Drop foreign key constraint and add new one
    op.drop_constraint(op.f("resources_user_id_fkey"), "resources", type_="foreignkey")
    op.create_foreign_key(None, "resources", "users", ["owner_id"], ["id"])

    # Drop old columns
    op.drop_column("resources", "url")
    op.drop_column("resources", "user_id")
    op.drop_column("resources", "raw_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resources",
        sa.Column("raw_text", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "resources",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "resources", sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "resources", type_="foreignkey")
    op.create_foreign_key(
        op.f("resources_user_id_fkey"), "resources", "users", ["user_id"], ["id"]
    )
    op.drop_column("resources", "prefer_provider")
    op.drop_column("resources", "original_content")
    op.drop_column("resources", "content_type")
    op.drop_column("resources", "owner_id")
    # ### end Alembic commands ###
