"""Add last_login_at to accounts table

Revision ID: cc7c5f32e20b
Revises: 8d7f1ec22b79
Create Date: 2026-03-15 01:44:39.048230

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc7c5f32e20b'
down_revision: Union[str, Sequence[str], None] = '8d7f1ec22b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(
        op.f('uq_users_email'), 'users', ['email'],
        postgresql_nulls_not_distinct=False
    )
    op.drop_column('accounts', 'last_login_at')
    # ### end Alembic commands ###
