"""add categories table with system seed data

Revision ID: d6c000ccd5ba
Revises: ea78e7455c2f
Create Date: 2026-03-25 23:18:29.823330

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6c000ccd5ba"
down_revision: Union[str, Sequence[str], None] = "ea78e7455c2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)

    # Add unique constraint for user categories (case-insensitive name per user)
    op.execute("""
        CREATE UNIQUE INDEX idx_categories_user_name_unique
        ON categories (owner_id, LOWER(name))
        WHERE owner_id IS NOT NULL
    """)

    # Add unique constraint for system categories (case-insensitive name for system)
    op.execute("""
        CREATE UNIQUE INDEX idx_categories_system_name_unique
        ON categories (LOWER(name))
        WHERE owner_id IS NULL
    """)

    # Seed system categories (idempotent)
    system_categories = [
        "Technology",
        "Science",
        "Business",
        "Arts",
        "Health",
        "Education",
        "Politics",
        "Entertainment",
        "Sports",
        "Philosophy",
    ]

    for category_name in system_categories:
        op.execute(
            text("""
                INSERT INTO categories (name, is_system, owner_id, created_at)
                VALUES (:name, true, NULL, NOW())
                ON CONFLICT DO NOTHING
            """).bindparams(name=category_name)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop custom unique indexes
    op.execute("DROP INDEX IF EXISTS idx_categories_user_name_unique")
    op.execute("DROP INDEX IF EXISTS idx_categories_system_name_unique")

    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
