"""add status_message to resources

Revision ID: fa8cb7e566ef
Revises: 9141aa9e76e4
Create Date: 2026-03-21 16:07:20.194102

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa8cb7e566ef"
down_revision: Union[str, Sequence[str], None] = "9141aa9e76e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resources", sa.Column("status_message", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "status_message")
    # ### end Alembic commands ###
